#ifndef _GENERATED_ASM_DEFINES_H
#define _GENERATED_ASM_DEFINES_H
/*
 * This file is autogenerated. If you need to change it,
 * edit arch/x86/asm-defines.c instead.
 *
 * ALL MANUAL CHANGES TO THIS FILE WILL BE LOST!
 */

#define PERCPU_LINUX_SP 4120 /* __builtin_offsetof(struct per_cpu, linux_sp)	# */
	
#define PERCPU_VMCB_RAX 9720 /* __builtin_offsetof(struct per_cpu, vmcb.rax)	# */
	
#define PERCPU_STACK_END 4096 /* __builtin_offsetof(struct per_cpu, stack) + FIELD_SIZEOF(struct per_cpu, stack)	# */
#define PERCPU_SIZE_ASM 24576 /* sizeof(struct per_cpu)	# */
#define LOCAL_CPU_BASE_ASM 549755879424 /* LOCAL_CPU_BASE	# */

#endif
